# src/test/resources/application.properties

spring.application.name=student-management
server.port=0

# In-memory DB for tests
spring.datasource.url=jdbc:h2:mem:studentdb;MODE=LEGACY;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true

# Disable migrations during tests
spring.flyway.enabled=false
spring.liquibase.enabled=false

# Quieter logs in CI
logging.level.org.springframework=warn
logging.level.org.hibernate=warn
